name: Voxel
author: Voxelune
main: dev.voxelune.voxel.VoxelPlugin
version: 2.0.0
api-version: '1.21'
load: POSTWORLD
depend: []
description: Ultimate plugin developer framework - Forge/Fabric for Paper plugins
website: https://github.com/voxelune/voxel
commands:
  voxel:
    description: Voxel developer framework
    permission: voxel.dev.use
    usage: /voxel <reload|devinfo>
permissions:
  voxel.dev.use:
    default: op
    description: Access to Voxel developer commands
  voxel.dev.reload:
    default: op
    description: Reload Voxel framework
  voxel.dev.info:
    default: op
    description: View Voxel development information